// frontend-react/frontend-react/src/App.jsx
import { useEffect, useState } from "react";
import "./App.css";
import {
  actualizarProducto,
  crearProducto,
  eliminarProducto,
  listarPaginado,
} from "./services/productoService";

const productoVacio = {
  nombre: "",
  descripcion: "",
  precio: 0,
  stock: 0,
  activo: true,
};

const TAMANIO_PAGINA = 10;

function App() {
  const [usuario, setUsuario] = useState("admin");
  const [clave, setClave] = useState("Admin_2026!");
  const [filtro, setFiltro] = useState("");
  const [productos, setProductos] = useState([]);
  const [pagina, setPagina] = useState(0);
  const [totalPaginas, setTotalPaginas] = useState(0);
  const [totalElementos, setTotalElementos] = useState(0);
  const [formulario, setFormulario] = useState(productoVacio);
  const [editando, setEditando] = useState(false);
  const [mensaje, setMensaje] = useState("");

  useEffect(() => {
    cargarProductos(pagina);
  }, [pagina]);

  async function cargarProductos(paginaSolicitada = pagina) {
    try {
      const datos = await listarPaginado(
        usuario,
        clave,
        paginaSolicitada,
        TAMANIO_PAGINA,
        filtro,
      );
      setProductos(datos.content);
      setTotalPaginas(datos.totalPages);
      setTotalElementos(datos.totalElements);
      setPagina(datos.number);
      setMensaje(
        `Mostrando página ${datos.number + 1} de ${datos.totalPages} (${datos.totalElements} productos activos)`,
      );
    } catch (error) {
      manejarError(error);
    }
  }

  function buscar() {
    setPagina(0);
    cargarProductos(0);
  }

  function paginaAnterior() {
    if (pagina > 0) setPagina(pagina - 1);
  }

  function paginaSiguiente() {
    if (pagina + 1 < totalPaginas) setPagina(pagina + 1);
  }

  function cambiarCampo(event) {
    const { name, value, type, checked } = event.target;
    setFormulario({
      ...formulario,
      [name]: type === "checkbox" ? checked : value,
    });
  }

  async function guardar(event) {
    event.preventDefault();

    const producto = {
      ...formulario,
      precio: Number(formulario.precio),
      stock: Number(formulario.stock),
    };

    try {
      if (editando && producto.id) {
        await actualizarProducto(producto.id, producto, usuario, clave);
        setMensaje("Producto actualizado correctamente.");
        limpiarFormulario();
        await cargarProductos(pagina); // se queda en la MISMA página
      } else {
        await crearProducto(producto, usuario, clave);
        setMensaje("Producto registrado correctamente.");
        limpiarFormulario();
        await cargarProductos(pagina);
      }
    } catch (error) {
      manejarError(error);
    }
  }

  function seleccionar(producto) {
    setFormulario({ ...producto });
    setEditando(true);
  }

  async function eliminar(producto) {
    try {
      await eliminarProducto(producto.id, usuario, clave);
      setMensaje("Producto eliminado (lógicamente) correctamente.");

      const eraUltimoDeSuPagina = productos.length === 1 && pagina > 0;
      await cargarProductos(eraUltimoDeSuPagina ? pagina - 1 : pagina);
    } catch (error) {
      manejarError(error);
    }
  }

  function limpiarFormulario() {
    setFormulario(productoVacio);
    setEditando(false);
  }

  function manejarError(error) {
    if (error.status === 401) {
      setMensaje("Credenciales incorrectas.");
    } else if (error.status === 403) {
      setMensaje("El usuario autenticado requiere rol ADMIN para esta acción.");
    } else if (error.status === 409) {
      setMensaje("Ya existe un producto con ese nombre.");
    } else {
      setMensaje(error.message || "Error inesperado.");
    }
  }

  return (
    <main className="contenedor">
      <h1>CRUD de productos - React</h1>

      <section className="tarjeta">
        <h2>Credenciales</h2>
        <label>Usuario</label>
        <input value={usuario} onChange={(e) => setUsuario(e.target.value)} />

        <label>Contraseña</label>
        <input
          type="password"
          value={clave}
          onChange={(e) => setClave(e.target.value)}
        />
      </section>

      <section className="tarjeta">
        <h2>{editando ? "Editar producto" : "Registrar producto"}</h2>

        <form onSubmit={guardar}>
          <label>Nombre</label>
          <input
            name="nombre"
            value={formulario.nombre}
            onChange={cambiarCampo}
            required
          />

          <label>Descripción</label>
          <input
            name="descripcion"
            value={formulario.descripcion}
            onChange={cambiarCampo}
            required
          />

          <label>Precio</label>
          <input
            name="precio"
            type="number"
            value={formulario.precio}
            onChange={cambiarCampo}
            required
          />

          <label>Stock</label>
          <input
            name="stock"
            type="number"
            value={formulario.stock}
            onChange={cambiarCampo}
            required
          />

          <label>
            <input
              name="activo"
              type="checkbox"
              checked={formulario.activo}
              onChange={cambiarCampo}
            />
            Activo
          </label>

          <button type="submit">{editando ? "Actualizar" : "Guardar"}</button>
          <button type="button" onClick={limpiarFormulario}>
            Limpiar
          </button>
        </form>
      </section>

      <section className="tarjeta">
        <h2>Listado de productos (paginado)</h2>
        <input
          value={filtro}
          onChange={(e) => setFiltro(e.target.value)}
          placeholder="Buscar por nombre"
        />
        <button onClick={buscar}>Buscar</button>

        <p className="mensaje">{mensaje}</p>

        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Precio</th>
              <th>Stock</th>
              <th>Activo</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {productos.map((producto) => (
              <tr key={producto.id}>
                <td>{producto.id}</td>
                <td>{producto.nombre}</td>
                <td>{producto.precio}</td>
                <td>{producto.stock}</td>
                <td>{producto.activo ? "Sí" : "No"}</td>
                <td>
                  <button onClick={() => seleccionar(producto)}>Editar</button>
                  <button onClick={() => eliminar(producto)}>Eliminar</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="paginador">
          <button onClick={paginaAnterior} disabled={pagina === 0}>
            Anterior
          </button>
          <span>
            Página {totalPaginas === 0 ? 0 : pagina + 1} de {totalPaginas} (
            {totalElementos} productos)
          </span>
          <button
            onClick={paginaSiguiente}
            disabled={pagina + 1 >= totalPaginas}
          >
            Siguiente
          </button>
        </div>
      </section>
    </main>
  );
}

export default App;

// frontend-angular/frontend-angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { Producto } from './models/producto';
import { ProductoService } from './services/producto';

const TAMANIO_PAGINA = 10;

@Component({
  selector: 'app-root',
  imports: [CommonModule, FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnInit {
  usuario = 'admin';
  clave = 'Admin_2026!';
  filtro = '';

  productos: Producto[] = [];
  pagina = 0;
  totalPaginas = 0;
  totalElementos = 0;

  producto: Producto = {
    nombre: '',
    descripcion: '',
    precio: 0,
    stock: 0,
    activo: true,
  };

  editando = false;
  idEditando: number | null = null;
  mensaje = '';

  constructor(private productoService: ProductoService) {}

  ngOnInit(): void {
    this.listarProductos(0);
  }

  listarProductos(pagina: number): void {
    this.productoService
      .listarPaginado(this.usuario, this.clave, pagina, TAMANIO_PAGINA, this.filtro)
      .subscribe({
        next: (respuesta) => {
          this.productos = respuesta.content;
          this.totalPaginas = respuesta.totalPages;
          this.totalElementos = respuesta.totalElements;
          this.pagina = respuesta.number;
          this.mensaje = `Mostrando página ${this.pagina + 1} de ${this.totalPaginas} (${this.totalElementos} productos activos)`;
        },
        error: (error) => {
          this.manejarError(error);
        },
      });
  }

  buscar(): void {
    this.listarProductos(0);
  }

  paginaAnterior(): void {
    if (this.pagina > 0) {
      this.listarProductos(this.pagina - 1);
    }
  }

  paginaSiguiente(): void {
    if (this.pagina + 1 < this.totalPaginas) {
      this.listarProductos(this.pagina + 1);
    }
  }

  guardarProducto(): void {
    if (this.editando && this.idEditando !== null) {
      this.productoService
        .actualizar(this.idEditando, this.producto, this.usuario, this.clave)
        .subscribe({
          next: () => {
            this.mensaje = 'Producto actualizado correctamente.';
            this.limpiarFormulario();
            this.listarProductos(this.pagina); // misma página
          },
          error: (error) => this.manejarError(error),
        });
    } else {
      this.productoService.crear(this.producto, this.usuario, this.clave).subscribe({
        next: () => {
          this.mensaje = 'Producto registrado correctamente.';
          this.limpiarFormulario();
          this.listarProductos(this.pagina);
        },
        error: (error) => this.manejarError(error),
      });
    }
  }

  editarProducto(producto: Producto): void {
    this.editando = true;
    this.idEditando = producto.id ?? null;

    this.producto = {
      nombre: producto.nombre,
      descripcion: producto.descripcion,
      precio: producto.precio,
      stock: producto.stock,
      activo: producto.activo,
    };
  }

  eliminarProducto(id: number | undefined): void {
    if (id === undefined) {
      this.mensaje = 'No se puede eliminar un producto sin id.';
      return;
    }

    const eraUltimoDeSuPagina = this.productos.length === 1 && this.pagina > 0;

    this.productoService.eliminar(id, this.usuario, this.clave).subscribe({
      next: () => {
        this.mensaje = 'Producto eliminado (lógicamente) correctamente.';
        this.listarProductos(eraUltimoDeSuPagina ? this.pagina - 1 : this.pagina);
      },
      error: (error) => this.manejarError(error),
    });
  }

  limpiarFormulario(): void {
    this.editando = false;
    this.idEditando = null;

    this.producto = {
      nombre: '',
      descripcion: '',
      precio: 0,
      stock: 0,
      activo: true,
    };
  }

  private manejarError(error: any): void {
    if (error.status === 401) {
      this.mensaje = 'Credenciales incorrectas.';
    } else if (error.status === 403) {
      this.mensaje = 'El usuario autenticado requiere rol ADMIN para esta acción.';
    } else if (error.status === 409) {
      this.mensaje = 'Ya existe un producto con ese nombre.';
    } else {
      this.mensaje = error.message || 'Error inesperado.';
    }
  }
}
